export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';

export const WISHLIST_NOT_VALID = "WISHLIST_NOT_WALID";
export const WISHLIST_VALID = "WISHLIST_VALID";